apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-ldaplib
  labels:
    app: openldap
spec:
  # storageClassName: ocs-storagecluster-cephfs
  storageClassName: lvms-vg1
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
